// web-next/app/lib/add-payment.tsx
import styles from "./add-payment.module.css";
import { revalidatePath } from "next/cache";

export default function AddPayment({companyId}: { companyId: number }) {

  async function addPayment(formData: FormData) {
    "use server"

    const data = {
      amount: formData.get("amount")
    };

    const res = await fetch(`http://payment.localhost/payments/${companyId}`, {
      method: "PUT",
      body: JSON.stringify(data),
      headers: {
        "Content-Type": "application/json"
      }
    });

    if (res.ok) {
      revalidatePath(`/${companyId}`);
    }
  }

  return <form className={styles.form} action={addPayment}>
    <p>Neue Beitragszahlung hinzufügen:</p>
    <div>
      <input type={"number"} min={"0.01"} step={"0.01"} id={"amount"} name={"amount"}/>
      <button type="submit">Hinzufügen</button>
    </div>
  </form>
}

// web-angular/src/lib/add-payment/add-payment.component.ts
import { Component, Input } from "@angular/core";
import { FormControl, FormGroup, ReactiveFormsModule } from "@angular/forms";
import { HttpClient } from "@angular/common/http";

@Component({
  selector: "app-add-payment",
  standalone: true,
  imports: [
    ReactiveFormsModule
  ],
  templateUrl: "./add-payment.component.html",
  styleUrl: "./add-payment.component.css"
})
export class AddPaymentComponent {
  @Input() companyId!: number;

  addPaymentForm = new FormGroup({
    amount: new FormControl()
  });

  constructor(private http: HttpClient) {
  }

  addPayment() {
    this.http.put(`http://payment.localhost/payments/${this.companyId}`, this.addPaymentForm.value).subscribe(() => {
      window.location.reload();
    });
  }
}

<form (ngSubmit)="addPayment()" [formGroup]="addPaymentForm">
    <p>Neue Beitragszahlung hinzufügen:</p>
    <div>
        <input formControlName="amount" id="amount" min="0.01" step="0.01" type="number"/>
        <button type="submit">Hinzufügen</button>
    </div>
</form>
