// web-next/app/page.tsx
import styles from "@/app/page.module.css";
import Image from "next/image";
import { Company } from "@/types";
import Link from "next/link";

export const revalidate = 60;

export default async function Home() {
  const res = await fetch('http://company.localhost/companies');
  let companies: Company[] = await res.json();

  return (
    <div className={styles.page}>
      <div className={styles.title}>
        <Image src="./icon.svg" alt="Logo der Nürnberger Versicherung" width="40" height="40"/>
        <h1>Beitragsverwaltung</h1>
      </div>
      <table className={styles.table}>
        <thead>
        <tr>
          <th>Firmenname</th>
          <th>Aktionen</th>
        </tr>
        </thead>
        <tbody>
        {companies.map(company =>
          <tr key={company.id}>
            <td>{company.name}</td>
            <td>
              <Link className={styles.load} href={`/${company.id}`}>Details anzeigen</Link>
            </td>
          </tr>)}
        </tbody>
      </table>
    </div>
  )
    ;
}

// web/src/app/app.component.ts
import { Component, OnInit } from "@angular/core";
import { CurrencyPipe, NgForOf, NgIf, NgOptimizedImage } from "@angular/common";
import { Company } from "../lib/types";
import { HttpClient } from "@angular/common/http";

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  imports: [
    NgForOf,
    NgIf,
    CurrencyPipe,
    NgOptimizedImage
  ],
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {

  companies?: Company[];
  company?: Company;

  constructor(private http: HttpClient) {
  }

  ngOnInit() {
    this.http.get<Company[]>('http://company.localhost/companies')
      .subscribe(res => this.companies = res);
  }

  loadCompanyDetails(id: number) {
    this.http.get<Company>(`http://company.localhost/companies/${id}`)
      .subscribe(res => this.company = res);
  }

  closeDetails() {
    this.company = undefined;
  }
}

<div class="title">
    <img ngSrc="./icon.svg" alt="Logo der Nürnberger Versicherung" width="40" height="40">
    <h1>Beitragsverwaltung</h1>
</div>
<table class="company-table">
    <thead>
    <tr>
        <th>Firmenname</th>
        <th>Aktionen</th>
    </tr>
    </thead>
    <tbody>
    <tr *ngFor="let company of companies">
        <td>{{ company.name }}</td>
        <td>
            <button class="load-company" (click)="loadCompanyDetails(company.id)">Details anzeigen</button>
        </td>
    </tr>
    </tbody>
</table>
<div class="popover" *ngIf="company">
    <div class="content">
        <div class="header">
            <h1>{{ company.name }}</h1>
            <button (click)="closeDetails()" class="close">
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                     fill="#000000">
                    <path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/>
                </svg>
            </button>
        </div>
        <div>
            <p>Bisherige Beitragszahlungen:</p>
            <p *ngFor="let payment of company?.payments">{{ payment.amount | currency: 'EUR' }}</p>
        </div>
    </div>
</div>
